"""paths.py — パス解決モジュール

上方向探索で CLAUDE.md を見つけてプロジェクトルートを特定する。
全モジュール・スキルが共通で使うパス定数を提供する。
"""

from pathlib import Path

from constants import (
    CLAUDE_DIR_NAME,
    CLAUDE_MD_FILENAME,
    CODING_DIR_NAME,
    CODING_HUB_FILENAME,
    CODING_L2_PYTHON_FILENAME,
    CODING_L2_TYPESCRIPT_FILENAME,
    CODING_L3_CLOUDFLARE_FILENAME,
    CODING_L3_NEXTJS_FILENAME,
    DOCS_DIR_NAME,
    FEEDBACK_DIR_NAME,
    GITIGNORE_FILENAME,
    INDEX_FILENAME,
    LIBS_DIR_NAME,
    OS_SKILLS_FILENAME,
    RESEARCH_SHELF_NAME,
    SETTINGS_FILENAME,
    SKILLS_DIR_NAME,
    SPECS_DIR_NAME,
    STACKS_DIR_NAME,
    STARTER_DIR_NAME,
    STATE_DIR_NAME,
    TAG_ALIASES_FILENAME,
    TEMPLATES_DIR_NAME,
    UI_SPECS_DIR_NAME,
    VARIANT_FILE_NAME,
    VARIANT_GENERIC,
    VARIANT_NEXTJS,
    VERSION_CHECK_FILENAME,
    VERSION_FILENAME,
)

# NXT_ROOT: core/ の親ディレクトリ（nxt 本元ではリポジトリルート、PJ では .nxt-core/）
NXT_ROOT = Path(__file__).resolve().parent.parent


def find_project_root() -> Path | None:
    """CLAUDE.md を上方向探索してプロジェクトルートを特定する。"""
    current = Path(__file__).resolve().parent
    while current != current.parent:
        if (current / CLAUDE_MD_FILENAME).exists():
            return current
        current = current.parent
    return None


PROJECT_ROOT = find_project_root()

# nxt 本元/PJ 判定
IS_SOURCE = PROJECT_ROOT is not None and NXT_ROOT == PROJECT_ROOT

# 派生パス
LIBS_DIR = PROJECT_ROOT / LIBS_DIR_NAME if PROJECT_ROOT else None
STATE_DIR = PROJECT_ROOT / CLAUDE_DIR_NAME / STATE_DIR_NAME if PROJECT_ROOT else None
INDEX_FILE = STATE_DIR / INDEX_FILENAME if STATE_DIR else None
SPECS_DIR = NXT_ROOT / SPECS_DIR_NAME

# .libs/ サブディレクトリ
DESIGN_DIR = LIBS_DIR / "design" if LIBS_DIR else None
FEATURES_DIR = LIBS_DIR / "features" if LIBS_DIR else None
RESEARCH_DIR = LIBS_DIR / RESEARCH_SHELF_NAME if LIBS_DIR else None  # erqo-research の clone 先
RULES_DIR = LIBS_DIR / "rules" if LIBS_DIR else None
LOGS_DIR = LIBS_DIR / "session-logs" if LIBS_DIR else None

# プロジェクト派生パス
UI_SPECS_DIR = PROJECT_ROOT / UI_SPECS_DIR_NAME if PROJECT_ROOT else None
VERSION_FILE = NXT_ROOT / VERSION_FILENAME

# プロジェクトルート直下のファイル
CLAUDE_MD_FILE = PROJECT_ROOT / CLAUDE_MD_FILENAME if PROJECT_ROOT else None
GITIGNORE_FILE = PROJECT_ROOT / GITIGNORE_FILENAME if PROJECT_ROOT else None

# .claude/ 配下
SETTINGS_FILE = PROJECT_ROOT / CLAUDE_DIR_NAME / SETTINGS_FILENAME if PROJECT_ROOT else None
PROJECT_SKILLS_DIR = PROJECT_ROOT / CLAUDE_DIR_NAME / SKILLS_DIR_NAME if PROJECT_ROOT else None

# NXT_ROOT 配下（共通骨格）
SKILLS_SRC_DIR = NXT_ROOT / SKILLS_DIR_NAME

# variant 別装備 (stacks/<variant>/)
# stacks/ 直下を 1 箇所に集約し、各 variant 固有の装備はここから派生させる。
STACKS_DIR = NXT_ROOT / STACKS_DIR_NAME
STACK_NEXTJS_DIR = STACKS_DIR / VARIANT_NEXTJS
STACK_NEXTJS_SKILLS_DIR = STACK_NEXTJS_DIR / SKILLS_DIR_NAME
STACK_NEXTJS_DOCS_DIR = STACK_NEXTJS_DIR / DOCS_DIR_NAME
STACK_NEXTJS_TEMPLATES_DIR = STACK_NEXTJS_DIR / TEMPLATES_DIR_NAME
STACK_NEXTJS_STARTER_DIR = STACK_NEXTJS_DIR / STARTER_DIR_NAME
STACK_NEXTJS_SPECS_DIR = STACK_NEXTJS_DIR / SPECS_DIR_NAME
STACK_NEXTJS_CODING_DIR = STACK_NEXTJS_SPECS_DIR / CODING_DIR_NAME

# プタ子 (generic) 装備: 最小構成 (skills は空、starter は案内 README のみ)
STACK_GENERIC_DIR = STACKS_DIR / VARIANT_GENERIC
STACK_GENERIC_SKILLS_DIR = STACK_GENERIC_DIR / SKILLS_DIR_NAME
STACK_GENERIC_STARTER_DIR = STACK_GENERIC_DIR / STARTER_DIR_NAME

# Next.js 特化資産の実パス (docs.py / install.py / coding_rules.py から参照)
DOCS_DIR = STACK_NEXTJS_DOCS_DIR
TEMPLATES_DIR = STACK_NEXTJS_TEMPLATES_DIR

# specs/coding/ ハブ + 層別ファイル（coding_rules.py が返す）
CODING_HUB_FILE = SPECS_DIR / CODING_HUB_FILENAME
SPECS_CODING_DIR = SPECS_DIR / CODING_DIR_NAME
CODING_L2_PYTHON_FILE = SPECS_CODING_DIR / CODING_L2_PYTHON_FILENAME
CODING_L2_TYPESCRIPT_FILE = SPECS_CODING_DIR / CODING_L2_TYPESCRIPT_FILENAME
CODING_L3_NEXTJS_FILE = STACK_NEXTJS_CODING_DIR / CODING_L3_NEXTJS_FILENAME
CODING_L3_CLOUDFLARE_FILE = SPECS_CODING_DIR / CODING_L3_CLOUDFLARE_FILENAME

# .claude/state/ 配下のサブパス
OS_SKILLS_MANIFEST_FILE = STATE_DIR / OS_SKILLS_FILENAME if STATE_DIR else None
VERSION_CHECK_STATE_FILE = STATE_DIR / VERSION_CHECK_FILENAME if STATE_DIR else None
TAG_ALIASES_FILE = STATE_DIR / TAG_ALIASES_FILENAME if STATE_DIR else None
FEEDBACK_DIR = STATE_DIR / FEEDBACK_DIR_NAME if STATE_DIR else None
VARIANT_FILE = STATE_DIR / VARIANT_FILE_NAME if STATE_DIR else None
